export enum TicketStatus {
  OPEN = 'Abierto',
  CLOSED = 'Cerrado',
  REOPENED = 'Reabierto',
  SOLVED = 'Resuelto',
  REJECTED = 'Rechazado',
  ON_HOLD = 'En espera',
  IN_PROGRESS = 'En progreso',
  WAITING_FOR_CUSTOMER = 'Esperando a la revisión del cliente',
  WAITING_FOR_RESOLUTION = 'Esperando a la resolución',
  WAITING_FOR_CUSTOMER_RESPONSE = 'Esperando respuesta del cliente',
  WAITING_FOR_PARTNER_RESPONSE = 'Esperando respuesta del socio',
  WAITING_FOR_CUSTOMER_FEEDBACK = 'Esperando feedback del cliente',
  WAITING_FOR_PARTNER_FEEDBACK = 'Esperando feedback del socio',
  WAITING_FOR_CUSTOMER_FEEDBACK_AND_RESOLUTION = 'Esperando feedback del cliente y resolución',
  WAITING_FOR_PARTNER_FEEDBACK_AND_RESOLUTION = 'Esperando feedback del socio y resolución',
  WAITING_FOR_CUSTOMER_REVIEW = 'Esperando revisión del cliente',
  WAITING_FOR_PARTNER_REVIEW = 'Esperando revisión del socio',
}
