name: Deploy to Production on EasyPanel - https://demosfabriziodev.com/

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [unit, e2e]

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: push
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          API_SECRET: ${{ secrets.API_SECRET }}
        run: |
          curl -X GET "$WEBHOOK_URL/$API_SECRET"
